# Gradle Config Properties
# https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx1G

# Gradle General Properties
group=dev.noeul.minecraftmod
version=1.0.0
targetCompatibility=17
archivesBaseName=TemplateFabricMod

# Fabric Loader Properties
# https://fabricmc.net/develop/
# Parchment - https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data/
minecraft_version=1.21.1
#yarn_mappings=1.21.1+build.3
parchment_version=parchment-1.21:2024.07.28
loader_version=0.16.5

# Mod Properties
mod_id=templatemod
mod_name=Template Fabric Mod

# Dependencies
# Fabric API - https://fabricmc.net/develop/
# Mod Menu - https://modrinth.com/mod/modmenu/versions
fabric_api_version=0.105.0+1.21.1
mod_menu_version=11.+
