# Gradle Config Properties
# https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx1G

# Gradle General Properties
group=dev.noeul.minecraftmod
version=1.0.0
targetCompatibility=21
archivesBaseName=TemplateMod

# Fabric Loom Properties
fabric.loom.multiProjectOptimisation=true

# Mod Properties
mod_id=templatemod
mod_name=Template Mod

# Fabric Properties
# https://fabricmc.net/develop/
# Parchment - https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data/
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
#parchment_version=parchment-1.21.4:2025.02.16
loader_version=0.16.10

# Dependencies
# Fabric API - https://fabricmc.net/develop/
# Mod Menu - https://modrinth.com/mod/modmenu/versions
fabric_api_version=0.118.5+1.21.4
mod_menu_version=13.+
